name: vae-conv-percep-l1
data_root: /Users/justinbarry/projects/data/
dataset_name: 'celeba'
# dataset_name: 'cifar10'
# dataset_name: 'mnist'

batch_size: 8
image_size: 64
# image_size: 128
# image_size: 28
n_epochs: 3
num_channels: 3
# num_channels: 1

latent_dims: 128

num_workers: 4

artifact_name: jbarry-team/${project}/${name}-best-model:latest
download_data: False
wandb_mode: disabled

test_run: True
sample_size: 300

local_visualization: False
save_model: False
# save_model: True
# load_and_test_model: False
load_and_test_model: True
train_model: False
# train_model: True
summary: False
# summary: True

# model_type: mlp
# model_type: unet
# model_type: conv
model_type: aekl
compile: False