name: vae-conv-save
data_root: /Users/justinbarry/projects/data/
dataset_name: 'cifar10'

batch_size: 12
image_size: 224
n_epochs: 50
num_channels: 3

num_workers: 4

artifact_name: jbarry-team/${project}/${name}_best_model:v23
download_data: False
wandb_mode: disabled

local_visualization: False
save_model: False
load_and_test_model: True
train_model: False
summary: False

# model_type: mlp
# model_type: unet
model_type: conv