name: vae-conv-basic
data_root: /Users/justinbarry/projects/data/
dataset_name: 'celeba'
# dataset_name: 'cifar10'
# dataset_name: 'mnist'

batch_size: 8
image_size: 64
# image_size: 128
# image_size: 28
n_epochs: 3
num_channels: 3
# num_channels: 1

latent_dims: 4

num_workers: 4

artifact_name: jbarry-team/${project}/${name}_best_model:v20
download_data: False
wandb_mode: disabled

local_visualization: False
save_model: False
load_and_test_model: False
# load_and_test_model: False
# train_model: False
train_model: True
summary: False
# summary: True

# model_type: mlp
# model_type: unet
model_type: conv