name: vae-unet-local
data_root: /Users/justinbarry/projects/data/
dataset_name: 'cifar10'

batch_size: 8
image_size: 128
n_epochs: 20
num_channels: 3

num_workers: 4

artifact_name: jbarry-team/vae-cifar10/vae-local_best_model:latest
download_data: False
wandb_mode: disabled

local_visualization: False
save_model: True
load_and_test_model: False
train_model: True

# model_type: mlp
model_type: unet