name: vae-conv-save
data_root: /Users/justinbarry/projects/data/
# dataset_name: 'cifar10'
dataset_name: 'mnist'

batch_size: 128
# image_size: 224
image_size: 28
n_epochs: 4
# num_channels: 3
num_channels: 1

latent_dims: 16

num_workers: 4

artifact_name: jbarry-team/${project}/${name}_best_model:v23
download_data: False
wandb_mode: disabled

local_visualization: True
save_model: False
load_and_test_model: False
train_model: True
summary: False

model_type: mlp
# model_type: unet
# model_type: conv